### ISSUE TITLE
explodey stuff before version_compare() probably not required

### ISSUE THREAD

**Issue by xurizaemon** [eileenmcnaughton/nz.co.fuzion.accountsync#15]
Not a bug, just something which could be simpler. In https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/blob/master/CRM/Accountsync/Hook.php#L21 I see this is manually breaking up version strings. I think it probably doesn't need to.

```
php > $versions = array(
php (         '4.6.9-dev',
php (         '4.6.9-alpha1',
php (         '4.6.9-alpha2',
php (         '4.6.9-beta1',
php (         '4.6.9-rc1',
php (         '4.6.9-release1',
php (         '4.6.9',
php (         '4.6.8.1',
php (         '4.4',
php (         '4.5',
php (         '4.4.234',
php (         '4.5.678',
php (         '4.5-11223'
php (       );
php > usort($versions, 'version_compare');
php > print_r($versions);
Array
(
    [0] => 4.4
    [1] => 4.4.234
    [2] => 4.5
    [3] => 4.5.678
    [4] => 4.5-11223
    [5] => 4.6.8.1
    [6] => 4.6.9-release1
    [7] => 4.6.9-dev
    [8] => 4.6.9-alpha1
    [9] => 4.6.9-alpha2
    [10] => 4.6.9-beta1
    [11] => 4.6.9-rc1
    [12] => 4.6.9
)
```

I reckon if you just remove the explodes and use [version_compare()](http://php.net/manual/en/function.version-compare.php) neat, you'll find it does what it should. (If it doesn't, then maybe the version string is too funky?)

**Comment by xurizaemon** [comment]
OK so item 4 in the above list is a "broken" version string, maybe CiviCRM's does need special treatment then?

**Comment by mattwire** [comment]
@eileenmcnaughton I think this code has long gone and this issue can be closed

**Comment by eileenmcnaughton** [comment]
yep!
