### ISSUE TITLE
Catch mismatches rather than throwing fatal errors

### ISSUE THREAD

**Issue by xurizaemon** [eileenmcnaughton/nz.co.fuzion.accountsync#17]
In the case where a line item doesn't result in a financial type => contact lookup result, the extension would bail out with a fatal error (presumably halting progress at some mismatched transaction).

By checking the result of earlier queries, this can be handled more gracefully, eg by recording the contribution but omitting the match we tried to make (so, no contact ID associated).

Please give this a try - YES site seems to have some suitable test data for it :)

**Comment by xurizaemon** [comment]
If `CRM_Financial_BAO_FinancialAccount::getAccountingCode($financialTypeID)` didn't return a result, this would feed an empty ID back into `CRM_Accountsync_BAO_AccountInvoice::getAccountsContact() which in turn would fatal on the invalid SQL generated. Then no more line items will get processed.

Not returning empty string / checking result should allow this to be handled more gracefully, hopefully here by recording the line item but leaving the associated contact ID empty.

I'm not sure if *that* result is what you want, but it might be better than not handling the contribution or any that come after it!

**Comment by mattwire** [comment]
@eileenmcnaughton I think this can be closed

**Comment by eileenmcnaughton** [comment]
yay thanks @mattwire
