### ISSUE TITLE
tapestrymultiaccounts_get_civicrm_account_code

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.accountsync#2]
Eileen, when I run the "CiviXero Invoice Push Job" I get an error ...

    PHP Fatal error:  Call to undefined function tapestrymultiaccounts_get_civicrm_account_code() in nz.co.fuzion.accountsync/CRM/Accountsync/BAO/AccountInvoice.php on line 194

I suspect I need to supply a local copy of this function? What's the purpose of this call?

Thanks!

**Comment by eileenmcnaughton** [comment]
Argh - did I really commit that! This is the function

/**
 * Get the accounting code from the financial type id.
 *
 * @param int $financialTypeID
 *
 * @return mixed
 */
function tapestrymultiaccounts_get_civicrm_account_code($financialTypeID) {
  static $codes = array();
  if (!in_array($financialTypeID, $codes)) {
    $codes[$financialTypeID] = CRM_Financial_BAO_FinancialAccount::getAccountingCode($financialTypeID);
  }
  return $codes[$financialTypeID];
}

but, it's supposed to be in the main module!

NB - I did a fairly big change to Xero integration to facilitate multiple accounts for them - which I'm still testing

**Comment by eileenmcnaughton** [comment]
Ok - I got rid of that!
