### ISSUE TITLE
Do not change date of contribution when it is completed from Xero

### ISSUE THREAD

**Issue by eileenmcnaughton** [eileenmcnaughton/nz.co.fuzion.accountsync#27]
Arguably we could go with a setting for this but I think it doesn't make sense to update the receive_date based on the sync, as the sync may be done some time after the payment comes in - e.g if people reconcile once a week

**Comment by eileenmcnaughton** [comment]
@agileware let me know if you think this change will cause you problems - I could go with a setting.... or something more complex

**Comment by agileware** [comment]
@eileenmcnaughton I don't see that this was cause any more problems with the receive date anyway.  It would be good if we can actually be ( / having the option of) updating the date based on when the money hit the account in question - but on the other hand I don't think we have anyone integrating with Xero that is also relying on the receive date in CiviCRM for anything.

**Comment by eileenmcnaughton** [comment]
Thanks - let's worry about it if someone starts to care :-)
