### ISSUE TITLE
PayPal IPNs from pre 4.7 do not create AccountInvoices

### ISSUE THREAD

**Issue by agileware** [eileenmcnaughton/nz.co.fuzion.accountsync#31]
(Agileware ticket reference is CIVICRM-192)

PayPal IPNs in CiviCRM 4.6- do not always trigger AccountSync to create an AccountInvoice entity.

This appears to be because the `civicrm/extern/ipn.php` script does not (always?) load up the extensions to process contribution & line item hooks

We found a workaround was to create a Cron Job that would manually add these.

IPNs created in CiviCRM 4.7+ use a registered menu path, so CiviCRM is fully bootstrapped when they're processed.
Not sure if there's an upgrade process for these though, so recurring payments made in < 4.7 would still hit the extern script.

**Comment by agileware** [comment]
[workaround job as a gist](https://gist.github.com/agileware/0c516533b803e7d899c8b0e8a831024f)

**Comment by eileenmcnaughton** [comment]
I think the new ip path does work in 4.6 if you hack your install to use it. I don't really support pre 4.7 anymore so I guess I should update the .info file & drop a new release that specifies 4.7 as the only version at some stage.

In the meantime - I guess this is really just for tracking the issue & workaround

**Comment by eileenmcnaughton** [comment]
closing as it relates to unsupported version
