### ISSUE TITLE
account_invoice v AccountInvoice

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.accountsync#5]
I've noticed an inconsistency in the use of account_invoice and AccountInvoice

*API Entity*

If I try to edit the Scheduled Jobs "CiviAccountSync Cancel Contributions" and "CiviAccountSync Complete Contributions" it fails because the API Entity field is "account_invoice" which is invalid - it should be "AccountInvoice" (this is the option in the dropdown). I note that Job/job.mgd.php uses "account_invoice" when defining these jobs

**Comment by eileenmcnaughton** [comment]
I checked with Coleman and he confirmed that AccountInvoice is correct

**Comment by eileenmcnaughton** [comment]
I've updated references to AccountInvoice. Not sure what the mgd update will do - might need nursing... as I don't know if it will alter what is in the civicrm_managed table & if so, in what way
