### ISSUE TITLE
handling cancelled participation and refunds

### ISSUE THREAD

**Issue by ananelson** [eileenmcnaughton/nz.co.fuzion.accountsync#56]
Context: I'm actively developing both the Eventbrite and Quickbooks Civi integrations.

When a participant requests a refund, or an event is cancelled and everyone is refunded, our accounting use case is that we will need to reconcile two payment transactions: the original payment and the subsequent refund. Frequently these fall in different months since it can take a few weeks to decide to cancel an event, the another week for the refund to process, and hence the transaction will still be open at month end (and it's a pain to reconcile an account with missing transactions even if they net out within a month). (We're doing this in Eventbrite/PayPal but AFAIK that shouldn't matter.)

Ideally for us, what gets synced to our accounting system would be:
- a contribution for $30 on original purchase date
- a 2nd contribution for -$30 on cancellation date
- a payment for $30 on original purchase date
- a 2nd payment for -$30 on cancellation date

There are various other ways this could work too - I wanted to have a discussion (or be pointed to a prior discussion, or be told where's a better place to have this discussion) to get some clarity and perhaps suggest some code changes in one or more extensions. Maybe there can be a setting for preferred behavior. I'm happy to contribute on this.

**Comment by eileenmcnaughton** [comment]
I think the design intent in general is that the original contribution would have 2 payments against it - 1 positive & one negative on the appropriate dates - leaving the actual contribution value as zero - this correlates to the idea of a cancelled or voided invoice.

Having said that, I know lots of sites have opted to use negative contributions for various practical reasons

**Comment by ananelson** [comment]
As far as you are aware, should _accountsync_ recognize refunded contributions with $0 value and pos/neg payments and push these for syncing?

**Comment by eileenmcnaughton** [comment]
@ananelson hmm - I'm pretty sure Xero requires negative contributions to be treated as purchases & positive as sales so they are treated differently there - I *think* that logic belongs in CiviXero not accountsync though but I would have to check

@jitendrapurohit @mattwire & @agileware-fj  have all been contributing

**Comment by ananelson** [comment]
@eileenmcnaughton More generally, if there are some types of contribution which are synced to some accounts packages and not others, and accountsync is the gatekeeper for what goes in the sync table, how do we handle this?

**Comment by eileenmcnaughton** [comment]
@ananelson so the approach that I've used so far has been to team it with the connector extension https://github.com/eileenmcnaughton/nz.co.fuzion.connectors - this works on the assumption that different financial accounts might be synced with different packages - but you are thinking more about amounts huh?

**Comment by ananelson** [comment]
Good to know. But right - we're just syncing to 1 package (QBO). And it's not so much amounts (logic about amounts can go in the package-specific extension) but a binary of whether to sync the invoice or not.

**Comment by ananelson** [comment]
@eileenmcnaughton e.g. maybe accountsync can have a package setting for whether refunded contributions should be synced?

**Comment by eileenmcnaughton** [comment]
@ananelson I think it makes sense to add a setting like that - it would be defined in https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/blob/master/settings/AccountSync.setting.php

What would be the option is_sync_zero_value_contributions or is it more than a bool

**Comment by ananelson** [comment]
is_sync_zero_value or is_sync_refunded I think ... or maybe sync_statuses and it's a list? In general I don't think we care about zero value contributions *unless* they are refunded or cancelled and then the downstream package can decide how to represent that for the accounting package.

**Comment by eileenmcnaughton** [comment]
I think there is already a sync status setting actually https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/blob/master/settings/AccountSync.setting.php#L134

**Comment by ananelson** [comment]
Yes - thank you & apologies. Implemented in downstream package.
