### ISSUE TITLE
Protected methods halt cancel and complete jobs

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.accountsync#6]
Eileen, 

when I run the CiviAccountSync Cancel/Complete Contributions jobs, I get the following fatal errors

    PHP Fatal error:  Call to protected method CRM_Accountsync_BAO_AccountInvoice::cancelContributionFromAccountsStatus() from context '' in nz.co.fuzion.accountsync/api/v3/AccountInvoice.php on line 191

    PHP Fatal error:  Call to protected method CRM_Accountsync_BAO_AccountInvoice::completeContributionFromAccountsStatus() from context '' in nz.co.fuzion.accountsync/api/v3/AccountInvoice.php on line 187

Removing the "protected" keyword allows both jobs to run.

**Comment by eileenmcnaughton** [comment]
OK - looks like I was overzealous in the scope!
