### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by mattwire** [eileenmcnaughton/nz.co.fuzion.accountsync#68]
In https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/pull/63/commits/d4121643b2d11e60a8f6293722a675a5193a618d I've moved the Accounts menu items to Administer->CiviContribute->Accounts System.

Why?
- It is not very convenient / maintainable to force the accounts provider (eg. Xero / Quickbooks) to create menu entries for the generic forms/searches provided by AccountSync.
- If you have two accounts providers installed (unlikely but possible) then you have duplicate menu entries created to do the same thing.

This way, all entries for the accounts system appear under a standard menu item "Accounts System" meaning that we can write generic documentation, we don't need to have code in accounts specific extensions to show generic accounts system menu items and we can improve / move generic accounts system searches/forms without needing to update other extensions.

@eileenmcnaughton

**Comment by eileenmcnaughton** [comment]
@mattwire ok - I wonder if Accounts Integration would be better though? Or accounting integration - although the length of the string might be an issue

**Comment by mattwire** [comment]
> @mattwire ok - I wonder if Accounts Integration would be better though? Or accounting integration - although the length of the string might be an issue

Happy to go with whatever name you prefer :-)

**Comment by eileenmcnaughton** [comment]
@mattwire I probably prefer 'Integration' over 'System' cos it's more accurate - but if the string length doesn't work in the menu then System is OK

**Comment by mattwire** [comment]
Ok, see #70
