### ISSUE TITLE
account_status_id default to 0 which is not a valid value

### ISSUE THREAD

**Issue by samuelsov** [eileenmcnaughton/nz.co.fuzion.accountsync#75]
I see that the default of `accounts_status_id` was changed from NULL to 0.

Then the field was defined as a pseudoconstant which only allows for 1,2,3 options as seen here :
https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/commit/2a62ad4ca3bda629ef3907d22b3c3aeecf98c004#diff-b0be61fb062bb135843434608e371ebcabb67d519a10288cd18f73365fde8915

This lead to some oddities when we do the following:
1. save an entry in civicrm_account_invoice without accounts_status_id
2. load the civicrm_account_invoice
3. saved it without touching accounts_status_id

Which gives the error: 
`'0' is not a valid option for field accounts_status_id.`

I got this error in au.com.agileware.civiquickbooks when I tryed pushing a contribution that used to fail.

Is there a reason to keep the default accounts_status_id to 0 ?

**Comment by eileenmcnaughton** [comment]
@samuelsov I feel like we should perhaps change the default to 2 (pending) or else make the field required - what do you think?

**Comment by samuelsov** [comment]
In this case, as there is a synchronization error, we don't have an `accounts_invoice_id` so we definitely have no clue if there is an invoice in the external system or not. I'd rather stick to NULL when there is no `accounts_invoice_id` or if you prefer keep 0 as default and simply add an option 0 => 'Unknown' or something similar ?

**Comment by eileenmcnaughton** [comment]
@samuelsov OK - I'm OK with it being switched back to NULL or adding the extra option - whichever is easier - the extra option might be easier if there are type hints to battle

**Comment by samuelsov** [comment]
Great, thanks!
