### ISSUE TITLE
Logging table log_civicrm_account_contact can become huge

### ISSUE THREAD

**Issue by mlutfy** [eileenmcnaughton/nz.co.fuzion.accountsync#78]
I sometimes see the  `log_civicrm_account_contact` grow more than 500 MB, approx. 300k rows.

Would it be best to exclude the table from logging, or find a way to avoid updating all rows?

```
> select count(*), log_action from log_civicrm_account_contact group by log_action;
+----------+------------+
| count(*) | log_action |
+----------+------------+
|      121 | Insert     |
|   286727 | Update     |
|       10 | Delete     |
+----------+------------+
```

I have to admit I had a look at the code, but couldn't see where the update might be happening.

**Comment by eileenmcnaughton** [comment]
@mlutfy I think it is reasonable to exclude - @mattwire  @petednz do you ever use it for forensics??

**Comment by petednz** [comment]
I don't recall using this but i do recall it causing us problems. In particular i think if you set the Start Date in the past then the system will clog up with rows in log_civicrm_account_contact so once you have your contacts synched set the Start Date to 'now'

**Comment by mattwire** [comment]
Well it *is* a useful table for forensics but it does grow significantly on some sites. A site making heavy use of Xero currently has log_civicrm_account_contact at 92M and log_civicrm_account_invoice at 552M. Note that I'm using my own branch of Xero/accountsync that rewrites some of the sync handling. It would be good to work out *why* they grow so much but I don't think excluding them from logging is the right approach

**Comment by petednz** [comment]
Thx for all your work on this @mattwire

**Comment by mlutfy** [comment]
@mattwire Thanks! We deployed this on a few sites.
