### ISSUE TITLE
What should happen during dedupe if both contacts have an account_contact?

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.accountsync#8]
Eileen,

Just wanting to explore this use case, and what might be the possible/likely outcomes.

It seems like an awkward situation if the contact being deleted in CiviCRM has invoices in Xero. If there were no Xero invoices the corresponding Xero contact could be ignored or even archived. If there are Xero invoices, the account_invoice records will be OK, but CiviCRM and Xero will book them to different contact records. 

But that's a business concern. The technical question is what should happen to the 2 account_contact records?
- Should we delete the account_contact for the deleted contact? I think so, as it seems pointless trying to synchronise a deleted record. (And if the record is subsequently recovered from trash, it can be resynchronised.)
- Should we modify the account_contact for the remaining contact? I think all that's needed is to mark the account_contact as 'needs update' so any changes (eg, a phone inherited from the deleted contact) can be synced.

Thoughts?

**Comment by eileenmcnaughton** [comment]
I guess ideally you would want the one that 'really should be merged' in Xero to be renamed in Xero - e.g from 'Robert Brown' to '(merge required with 20765) Robert Brown'

**Comment by kenwest** [comment]
The naming of the Xero record is done by the Push Contact job. When that runs we've lost track of what is the merged Contact Id. However, we can tell if the CiviCRM Contact being pushed is deleted.

For instance, my implementation of hook_civicrm_accountPushAlterMapped includes the following logic to change the name of the Xero Contact ...

    switch ($entity) {
      case 'contact' :
        $deletedSuffix = ' (deleted in CiviCRM)';
        if (!empty($data['contact_is_deleted']) && stristr($params['Name'], $deletedSuffix) === false) {
          $params['Name'] .= $deletedSuffix;
        }
        break;
      }

This allows users of Xero to be aware of which Contacts have been deleted in CiviCRM.

To implement a name change like "merge required with 20765" would probably require an additional column in the civicrm_account_contact table for remembering that.

**Comment by mattwire** [comment]
@eileenmcnaughton last commented in 2015 - we can probably close this!

**Comment by eileenmcnaughton** [comment]
ok
