### ISSUE TITLE
CiviCRM 4.6 'updates' a contact rather than 'trashing' it

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.accountsync#9]
Eileen, I'm using 4.6.2 and when I trash a contact the _accountsync_handle_contact_deletion() function is called with $op set to 'update' rather than 'trash'.

Looking at the code for 4.6.2 it seems 'trash' is no longer an operation.

Perhaps this function ought to be extended to check for 'update' and if the contact's is_deleted value is set. Thoughts? (I can have a go at that if you think it's a good idea.)

**Comment by eileenmcnaughton** [comment]
So, we would need to support 'trash' for pre-4.6 & update with 'is_deleted' as well? Makes sense

**Comment by kenwest** [comment]
It appears that CRM_Contact_BAO_Contact::contactTrashRestore() has been modified in 4.6 to pass a params array to CRM_Utils_Hook::pre() that is available to accountsync_civicrm_pre().

I can change _accountsync_handle_contact_deletion() to accept that argument. (That argument is set to CRM_Core_DAO::$_nullArray in 4.5.8.) Then the test is ...

    ($op == 'delete' || $op == 'trash' || ($op == 'update' && !empty($params['is_deleted']))) && ($entity == 'Contact')

The 'empty' selects the case when is_deleted is 1 (ie, a trash in 4.6) and excludes normal updates (in all versions) and 'restore from trash' in 4.6 (when is_deleted is 0)

**Comment by eileenmcnaughton** [comment]
hmm 4.6 is a bit old
